"""empty message

Revision ID: 32643973e72c
Revises: a0cb0df7bcef
Create Date: 2020-03-12 20:44:02.429600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32643973e72c'
down_revision = 'a0cb0df7bcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Boolean, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_column('order', 'subject')
    op.drop_column('order', 'sn')
    op.drop_column('order', 'payer_uid')
    op.drop_column('order', 'order_status')
    op.drop_column('order', 'description')
    op.drop_column('order', 'client_sn')
    # ### end Alembic commands ###
